
version: 2.1

orbs:
  node: circleci/node@7.1.1

jobs:
  build:
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install:
          node-version: '20.19.4'
      - run: node --version
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: export NODE_OPTIONS="--max-old-space-size=4096" && npm run build
          name: Run build
workflows:
  build:
    jobs:
      - build